# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body78(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enforcement_level': 'str',
        'policy': 'str'
    }

    attribute_map = {
        'enforcement_level': 'enforcement_level',
        'policy': 'policy'
    }

    def __init__(self, enforcement_level=None, policy=None):  # noqa: E501
        """Body78 - a model defined in Swagger"""  # noqa: E501
        self._enforcement_level = None
        self._policy = None
        self.discriminator = None
        if enforcement_level is not None:
            self.enforcement_level = enforcement_level
        if policy is not None:
            self.policy = policy

    @property
    def enforcement_level(self):
        """Gets the enforcement_level of this Body78.  # noqa: E501

        The enforcement level to apply to the policy.  # noqa: E501

        :return: The enforcement_level of this Body78.  # noqa: E501
        :rtype: str
        """
        return self._enforcement_level

    @enforcement_level.setter
    def enforcement_level(self, enforcement_level):
        """Sets the enforcement_level of this Body78.

        The enforcement level to apply to the policy.  # noqa: E501

        :param enforcement_level: The enforcement_level of this Body78.  # noqa: E501
        :type: str
        """

        self._enforcement_level = enforcement_level

    @property
    def policy(self):
        """Gets the policy of this Body78.  # noqa: E501

        The rules of the policy.  # noqa: E501

        :return: The policy of this Body78.  # noqa: E501
        :rtype: str
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this Body78.

        The rules of the policy.  # noqa: E501

        :param policy: The policy of this Body78.  # noqa: E501
        :type: str
        """

        self._policy = policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body78, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body78):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
