# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body32(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'template': 'str',
        'ttl': 'int'
    }

    attribute_map = {
        'key': 'key',
        'template': 'template',
        'ttl': 'ttl'
    }

    def __init__(self, key=None, template=None, ttl=None):  # noqa: E501
        """Body32 - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._template = None
        self._ttl = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if template is not None:
            self.template = template
        if ttl is not None:
            self.ttl = ttl

    @property
    def key(self):
        """Gets the key of this Body32.  # noqa: E501

        The OIDC key to use for generating tokens. The specified key must already exist.  # noqa: E501

        :return: The key of this Body32.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this Body32.

        The OIDC key to use for generating tokens. The specified key must already exist.  # noqa: E501

        :param key: The key of this Body32.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def template(self):
        """Gets the template of this Body32.  # noqa: E501

        The template string to use for generating tokens. This may be in string-ified JSON or base64 format.  # noqa: E501

        :return: The template of this Body32.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this Body32.

        The template string to use for generating tokens. This may be in string-ified JSON or base64 format.  # noqa: E501

        :param template: The template of this Body32.  # noqa: E501
        :type: str
        """

        self._template = template

    @property
    def ttl(self):
        """Gets the ttl of this Body32.  # noqa: E501

        TTL of the tokens generated against the role.  # noqa: E501

        :return: The ttl of this Body32.  # noqa: E501
        :rtype: int
        """
        return self._ttl

    @ttl.setter
    def ttl(self, ttl):
        """Sets the ttl of this Body32.

        TTL of the tokens generated against the role.  # noqa: E501

        :param ttl: The ttl of this Body32.  # noqa: E501
        :type: int
        """

        self._ttl = ttl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body32, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body32):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
