# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body40(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'versions': 'list[int]'
    }

    attribute_map = {
        'versions': 'versions'
    }

    def __init__(self, versions=None):  # noqa: E501
        """Body40 - a model defined in Swagger"""  # noqa: E501
        self._versions = None
        self.discriminator = None
        if versions is not None:
            self.versions = versions

    @property
    def versions(self):
        """Gets the versions of this Body40.  # noqa: E501

        The versions to unarchive. The versions will be restored and their data will be returned on normal get requests.  # noqa: E501

        :return: The versions of this Body40.  # noqa: E501
        :rtype: list[int]
        """
        return self._versions

    @versions.setter
    def versions(self, versions):
        """Sets the versions of this Body40.

        The versions to unarchive. The versions will be restored and their data will be returned on normal get requests.  # noqa: E501

        :param versions: The versions of this Body40.  # noqa: E501
        :type: list[int]
        """

        self._versions = versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body40, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body40):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
