# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body46(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accessor': 'str',
        'path': 'list[str]',
        'paths': 'list[str]'
    }

    attribute_map = {
        'accessor': 'accessor',
        'path': 'path',
        'paths': 'paths'
    }

    def __init__(self, accessor=None, path=None, paths=None):  # noqa: E501
        """Body46 - a model defined in Swagger"""  # noqa: E501
        self._accessor = None
        self._path = None
        self._paths = None
        self.discriminator = None
        if accessor is not None:
            self.accessor = accessor
        if path is not None:
            self.path = path
        if paths is not None:
            self.paths = paths

    @property
    def accessor(self):
        """Gets the accessor of this Body46.  # noqa: E501

        Accessor of the token for which capabilities are being queried.  # noqa: E501

        :return: The accessor of this Body46.  # noqa: E501
        :rtype: str
        """
        return self._accessor

    @accessor.setter
    def accessor(self, accessor):
        """Sets the accessor of this Body46.

        Accessor of the token for which capabilities are being queried.  # noqa: E501

        :param accessor: The accessor of this Body46.  # noqa: E501
        :type: str
        """

        self._accessor = accessor

    @property
    def path(self):
        """Gets the path of this Body46.  # noqa: E501

        Use 'paths' instead.  # noqa: E501

        :return: The path of this Body46.  # noqa: E501
        :rtype: list[str]
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this Body46.

        Use 'paths' instead.  # noqa: E501

        :param path: The path of this Body46.  # noqa: E501
        :type: list[str]
        """

        self._path = path

    @property
    def paths(self):
        """Gets the paths of this Body46.  # noqa: E501

        Paths on which capabilities are being queried.  # noqa: E501

        :return: The paths of this Body46.  # noqa: E501
        :rtype: list[str]
        """
        return self._paths

    @paths.setter
    def paths(self, paths):
        """Sets the paths of this Body46.

        Paths on which capabilities are being queried.  # noqa: E501

        :param paths: The paths of this Body46.  # noqa: E501
        :type: list[str]
        """

        self._paths = paths

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body46, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body46):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
