# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body105(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'diff': 'bool',
        'force': 'bool'
    }

    attribute_map = {
        'diff': 'diff',
        'force': 'force'
    }

    def __init__(self, diff=None, force=None):  # noqa: E501
        """Body105 - a model defined in Swagger"""  # noqa: E501
        self._diff = None
        self._force = None
        self.discriminator = None
        if diff is not None:
            self.diff = diff
        if force is not None:
            self.force = force

    @property
    def diff(self):
        """Gets the diff of this Body105.  # noqa: E501

        Enables a slower re-indexing which will perform a key level check to diagnose issues. Defaults false.  # noqa: E501

        :return: The diff of this Body105.  # noqa: E501
        :rtype: bool
        """
        return self._diff

    @diff.setter
    def diff(self, diff):
        """Sets the diff of this Body105.

        Enables a slower re-indexing which will perform a key level check to diagnose issues. Defaults false.  # noqa: E501

        :param diff: The diff of this Body105.  # noqa: E501
        :type: bool
        """

        self._diff = diff

    @property
    def force(self):
        """Gets the force of this Body105.  # noqa: E501

        Forces a complete re-indexing which only scans data available in the storage. Defaults false.  # noqa: E501

        :return: The force of this Body105.  # noqa: E501
        :rtype: bool
        """
        return self._force

    @force.setter
    def force(self, force):
        """Sets the force of this Body105.

        Forces a complete re-indexing which only scans data available in the storage. Defaults false.  # noqa: E501

        :param force: The force of this Body105.  # noqa: E501
        :type: bool
        """

        self._force = force

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body105, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body105):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
