# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body36(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'object',
        'options': 'object',
        'version': 'int'
    }

    attribute_map = {
        'data': 'data',
        'options': 'options',
        'version': 'version'
    }

    def __init__(self, data=None, options=None, version=None):  # noqa: E501
        """Body36 - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._options = None
        self._version = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if options is not None:
            self.options = options
        if version is not None:
            self.version = version

    @property
    def data(self):
        """Gets the data of this Body36.  # noqa: E501

        The contents of the data map will be stored and returned on read.  # noqa: E501

        :return: The data of this Body36.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Body36.

        The contents of the data map will be stored and returned on read.  # noqa: E501

        :param data: The data of this Body36.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def options(self):
        """Gets the options of this Body36.  # noqa: E501

        Options for writing a KV entry. Set the \"cas\" value to use a Check-And-Set operation. If not set the write will be allowed. If set to 0 a write will only be allowed if the key doesn’t exist. If the index is non-zero the write will only be allowed if the key’s current version matches the version specified in the cas parameter.  # noqa: E501

        :return: The options of this Body36.  # noqa: E501
        :rtype: object
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this Body36.

        Options for writing a KV entry. Set the \"cas\" value to use a Check-And-Set operation. If not set the write will be allowed. If set to 0 a write will only be allowed if the key doesn’t exist. If the index is non-zero the write will only be allowed if the key’s current version matches the version specified in the cas parameter.  # noqa: E501

        :param options: The options of this Body36.  # noqa: E501
        :type: object
        """

        self._options = options

    @property
    def version(self):
        """Gets the version of this Body36.  # noqa: E501

        If provided during a read, the value at the version number will be returned  # noqa: E501

        :return: The version of this Body36.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Body36.

        If provided during a read, the value at the version number will be returned  # noqa: E501

        :param version: The version of this Body36.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body36, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body36):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
