# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body90(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dr_operation_token': 'str',
        'text': 'str'
    }

    attribute_map = {
        'dr_operation_token': 'dr_operation_token',
        'text': 'text'
    }

    def __init__(self, dr_operation_token=None, text=None):  # noqa: E501
        """Body90 - a model defined in Swagger"""  # noqa: E501
        self._dr_operation_token = None
        self._text = None
        self.discriminator = None
        if dr_operation_token is not None:
            self.dr_operation_token = dr_operation_token
        if text is not None:
            self.text = text

    @property
    def dr_operation_token(self):
        """Gets the dr_operation_token of this Body90.  # noqa: E501

        DR root token used to authorize this request.  # noqa: E501

        :return: The dr_operation_token of this Body90.  # noqa: E501
        :rtype: str
        """
        return self._dr_operation_token

    @dr_operation_token.setter
    def dr_operation_token(self, dr_operation_token):
        """Sets the dr_operation_token of this Body90.

        DR root token used to authorize this request.  # noqa: E501

        :param dr_operation_token: The dr_operation_token of this Body90.  # noqa: E501
        :type: str
        """

        self._dr_operation_token = dr_operation_token

    @property
    def text(self):
        """Gets the text of this Body90.  # noqa: E501

        The text of the license.  # noqa: E501

        :return: The text of this Body90.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Body90.

        The text of the license.  # noqa: E501

        :param text: The text of this Body90.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body90, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body90):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
