# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body47(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'list[str]',
        'paths': 'list[str]',
        'token': 'str'
    }

    attribute_map = {
        'path': 'path',
        'paths': 'paths',
        'token': 'token'
    }

    def __init__(self, path=None, paths=None, token=None):  # noqa: E501
        """Body47 - a model defined in Swagger"""  # noqa: E501
        self._path = None
        self._paths = None
        self._token = None
        self.discriminator = None
        if path is not None:
            self.path = path
        if paths is not None:
            self.paths = paths
        if token is not None:
            self.token = token

    @property
    def path(self):
        """Gets the path of this Body47.  # noqa: E501

        Use 'paths' instead.  # noqa: E501

        :return: The path of this Body47.  # noqa: E501
        :rtype: list[str]
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this Body47.

        Use 'paths' instead.  # noqa: E501

        :param path: The path of this Body47.  # noqa: E501
        :type: list[str]
        """

        self._path = path

    @property
    def paths(self):
        """Gets the paths of this Body47.  # noqa: E501

        Paths on which capabilities are being queried.  # noqa: E501

        :return: The paths of this Body47.  # noqa: E501
        :rtype: list[str]
        """
        return self._paths

    @paths.setter
    def paths(self, paths):
        """Sets the paths of this Body47.

        Paths on which capabilities are being queried.  # noqa: E501

        :param paths: The paths of this Body47.  # noqa: E501
        :type: list[str]
        """

        self._paths = paths

    @property
    def token(self):
        """Gets the token of this Body47.  # noqa: E501

        Token for which capabilities are being queried.  # noqa: E501

        :return: The token of this Body47.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Body47.

        Token for which capabilities are being queried.  # noqa: E501

        :param token: The token of this Body47.  # noqa: E501
        :type: str
        """

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body47, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body47):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
