# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body26(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias_id': 'str',
        'alias_mount_accessor': 'str',
        'alias_name': 'str',
        'id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'alias_id': 'alias_id',
        'alias_mount_accessor': 'alias_mount_accessor',
        'alias_name': 'alias_name',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, alias_id=None, alias_mount_accessor=None, alias_name=None, id=None, name=None):  # noqa: E501
        """Body26 - a model defined in Swagger"""  # noqa: E501
        self._alias_id = None
        self._alias_mount_accessor = None
        self._alias_name = None
        self._id = None
        self._name = None
        self.discriminator = None
        if alias_id is not None:
            self.alias_id = alias_id
        if alias_mount_accessor is not None:
            self.alias_mount_accessor = alias_mount_accessor
        if alias_name is not None:
            self.alias_name = alias_name
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name

    @property
    def alias_id(self):
        """Gets the alias_id of this Body26.  # noqa: E501

        ID of the alias.  # noqa: E501

        :return: The alias_id of this Body26.  # noqa: E501
        :rtype: str
        """
        return self._alias_id

    @alias_id.setter
    def alias_id(self, alias_id):
        """Sets the alias_id of this Body26.

        ID of the alias.  # noqa: E501

        :param alias_id: The alias_id of this Body26.  # noqa: E501
        :type: str
        """

        self._alias_id = alias_id

    @property
    def alias_mount_accessor(self):
        """Gets the alias_mount_accessor of this Body26.  # noqa: E501

        Accessor of the mount to which the alias belongs to. This should be supplied in conjunction with 'alias_name'.  # noqa: E501

        :return: The alias_mount_accessor of this Body26.  # noqa: E501
        :rtype: str
        """
        return self._alias_mount_accessor

    @alias_mount_accessor.setter
    def alias_mount_accessor(self, alias_mount_accessor):
        """Sets the alias_mount_accessor of this Body26.

        Accessor of the mount to which the alias belongs to. This should be supplied in conjunction with 'alias_name'.  # noqa: E501

        :param alias_mount_accessor: The alias_mount_accessor of this Body26.  # noqa: E501
        :type: str
        """

        self._alias_mount_accessor = alias_mount_accessor

    @property
    def alias_name(self):
        """Gets the alias_name of this Body26.  # noqa: E501

        Name of the alias. This should be supplied in conjunction with 'alias_mount_accessor'.  # noqa: E501

        :return: The alias_name of this Body26.  # noqa: E501
        :rtype: str
        """
        return self._alias_name

    @alias_name.setter
    def alias_name(self, alias_name):
        """Sets the alias_name of this Body26.

        Name of the alias. This should be supplied in conjunction with 'alias_mount_accessor'.  # noqa: E501

        :param alias_name: The alias_name of this Body26.  # noqa: E501
        :type: str
        """

        self._alias_name = alias_name

    @property
    def id(self):
        """Gets the id of this Body26.  # noqa: E501

        ID of the entity.  # noqa: E501

        :return: The id of this Body26.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Body26.

        ID of the entity.  # noqa: E501

        :param id: The id of this Body26.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Body26.  # noqa: E501

        Name of the entity.  # noqa: E501

        :return: The name of this Body26.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body26.

        Name of the entity.  # noqa: E501

        :param name: The name of this Body26.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body26, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body26):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
