# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body98(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'secondary_public_key': 'str',
        'ttl': 'int'
    }

    attribute_map = {
        'id': 'id',
        'secondary_public_key': 'secondary_public_key',
        'ttl': 'ttl'
    }

    def __init__(self, id=None, secondary_public_key=None, ttl=None):  # noqa: E501
        """Body98 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._secondary_public_key = None
        self._ttl = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if secondary_public_key is not None:
            self.secondary_public_key = secondary_public_key
        if ttl is not None:
            self.ttl = ttl

    @property
    def id(self):
        """Gets the id of this Body98.  # noqa: E501

        An opaque identifier that can be used to identify and revoke a secondary cluster's access later.  # noqa: E501

        :return: The id of this Body98.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Body98.

        An opaque identifier that can be used to identify and revoke a secondary cluster's access later.  # noqa: E501

        :param id: The id of this Body98.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def secondary_public_key(self):
        """Gets the secondary_public_key of this Body98.  # noqa: E501

        A base64-encoded public key generated by the secondary cluster.  # noqa: E501

        :return: The secondary_public_key of this Body98.  # noqa: E501
        :rtype: str
        """
        return self._secondary_public_key

    @secondary_public_key.setter
    def secondary_public_key(self, secondary_public_key):
        """Sets the secondary_public_key of this Body98.

        A base64-encoded public key generated by the secondary cluster.  # noqa: E501

        :param secondary_public_key: The secondary_public_key of this Body98.  # noqa: E501
        :type: str
        """

        self._secondary_public_key = secondary_public_key

    @property
    def ttl(self):
        """Gets the ttl of this Body98.  # noqa: E501

        The TTL to use for the secondary activation token. Defaults to 30 minutes.  # noqa: E501

        :return: The ttl of this Body98.  # noqa: E501
        :rtype: int
        """
        return self._ttl

    @ttl.setter
    def ttl(self, ttl):
        """Sets the ttl of this Body98.

        The TTL to use for the secondary activation token. Defaults to 30 minutes.  # noqa: E501

        :param ttl: The ttl of this Body98.  # noqa: E501
        :type: int
        """

        self._ttl = ttl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body98, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body98):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
