# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hashicorp_vault_client
from api.identity_api import IdentityApi  # noqa: E501
from hashicorp_vault_client.rest import ApiException


class TestIdentityApi(unittest.TestCase):
    """IdentityApi unit test stubs"""

    def setUp(self):
        self.api = api.identity_api.IdentityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_identity_alias_id_id(self):
        """Test case for delete_identity_alias_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_delete_identity_entity_alias_id_id(self):
        """Test case for delete_identity_entity_alias_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_delete_identity_entity_id_id(self):
        """Test case for delete_identity_entity_id_id

        Update, read or delete an entity using entity ID  # noqa: E501
        """
        pass

    def test_delete_identity_entity_name_name(self):
        """Test case for delete_identity_entity_name_name

        Update, read or delete an entity using entity name  # noqa: E501
        """
        pass

    def test_delete_identity_group_alias_id_id(self):
        """Test case for delete_identity_group_alias_id_id

        """
        pass

    def test_delete_identity_group_id_id(self):
        """Test case for delete_identity_group_id_id

        Update or delete an existing group using its ID.  # noqa: E501
        """
        pass

    def test_delete_identity_group_name_name(self):
        """Test case for delete_identity_group_name_name

        """
        pass

    def test_delete_identity_oidc_key_name(self):
        """Test case for delete_identity_oidc_key_name

        CRUD operations for OIDC keys.  # noqa: E501
        """
        pass

    def test_delete_identity_oidc_role_name(self):
        """Test case for delete_identity_oidc_role_name

        CRUD operations on OIDC Roles  # noqa: E501
        """
        pass

    def test_delete_identity_persona_id_id(self):
        """Test case for delete_identity_persona_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_get_identity_alias_id(self):
        """Test case for get_identity_alias_id

        List all the alias IDs.  # noqa: E501
        """
        pass

    def test_get_identity_alias_id_id(self):
        """Test case for get_identity_alias_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_get_identity_entity_alias_id(self):
        """Test case for get_identity_entity_alias_id

        List all the alias IDs.  # noqa: E501
        """
        pass

    def test_get_identity_entity_alias_id_id(self):
        """Test case for get_identity_entity_alias_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_get_identity_entity_id(self):
        """Test case for get_identity_entity_id

        List all the entity IDs  # noqa: E501
        """
        pass

    def test_get_identity_entity_id_id(self):
        """Test case for get_identity_entity_id_id

        Update, read or delete an entity using entity ID  # noqa: E501
        """
        pass

    def test_get_identity_entity_name(self):
        """Test case for get_identity_entity_name

        List all the entity names  # noqa: E501
        """
        pass

    def test_get_identity_entity_name_name(self):
        """Test case for get_identity_entity_name_name

        Update, read or delete an entity using entity name  # noqa: E501
        """
        pass

    def test_get_identity_group_alias_id(self):
        """Test case for get_identity_group_alias_id

        List all the group alias IDs.  # noqa: E501
        """
        pass

    def test_get_identity_group_alias_id_id(self):
        """Test case for get_identity_group_alias_id_id

        """
        pass

    def test_get_identity_group_id(self):
        """Test case for get_identity_group_id

        List all the group IDs.  # noqa: E501
        """
        pass

    def test_get_identity_group_id_id(self):
        """Test case for get_identity_group_id_id

        Update or delete an existing group using its ID.  # noqa: E501
        """
        pass

    def test_get_identity_group_name(self):
        """Test case for get_identity_group_name

        """
        pass

    def test_get_identity_group_name_name(self):
        """Test case for get_identity_group_name_name

        """
        pass

    def test_get_identity_oidc_config(self):
        """Test case for get_identity_oidc_config

        OIDC configuration  # noqa: E501
        """
        pass

    def test_get_identity_oidc_key(self):
        """Test case for get_identity_oidc_key

        List OIDC keys  # noqa: E501
        """
        pass

    def test_get_identity_oidc_key_name(self):
        """Test case for get_identity_oidc_key_name

        CRUD operations for OIDC keys.  # noqa: E501
        """
        pass

    def test_get_identity_oidc_role(self):
        """Test case for get_identity_oidc_role

        List configured OIDC roles  # noqa: E501
        """
        pass

    def test_get_identity_oidc_role_name(self):
        """Test case for get_identity_oidc_role_name

        CRUD operations on OIDC Roles  # noqa: E501
        """
        pass

    def test_get_identity_oidc_token_name(self):
        """Test case for get_identity_oidc_token_name

        Generate an OIDC token  # noqa: E501
        """
        pass

    def test_get_identity_oidc_well_known_keys(self):
        """Test case for get_identity_oidc_well_known_keys

        Retrieve public keys  # noqa: E501
        """
        pass

    def test_get_identity_oidc_well_known_openid_configuration(self):
        """Test case for get_identity_oidc_well_known_openid_configuration

        Query OIDC configurations  # noqa: E501
        """
        pass

    def test_get_identity_persona_id(self):
        """Test case for get_identity_persona_id

        List all the alias IDs.  # noqa: E501
        """
        pass

    def test_get_identity_persona_id_id(self):
        """Test case for get_identity_persona_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_post_identity_alias(self):
        """Test case for post_identity_alias

        Create a new alias.  # noqa: E501
        """
        pass

    def test_post_identity_alias_id_id(self):
        """Test case for post_identity_alias_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_post_identity_entity(self):
        """Test case for post_identity_entity

        Create a new entity  # noqa: E501
        """
        pass

    def test_post_identity_entity_alias(self):
        """Test case for post_identity_entity_alias

        Create a new alias.  # noqa: E501
        """
        pass

    def test_post_identity_entity_alias_id_id(self):
        """Test case for post_identity_entity_alias_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass

    def test_post_identity_entity_id_id(self):
        """Test case for post_identity_entity_id_id

        Update, read or delete an entity using entity ID  # noqa: E501
        """
        pass

    def test_post_identity_entity_merge(self):
        """Test case for post_identity_entity_merge

        Merge two or more entities together  # noqa: E501
        """
        pass

    def test_post_identity_entity_name_name(self):
        """Test case for post_identity_entity_name_name

        Update, read or delete an entity using entity name  # noqa: E501
        """
        pass

    def test_post_identity_group(self):
        """Test case for post_identity_group

        Create a new group.  # noqa: E501
        """
        pass

    def test_post_identity_group_alias(self):
        """Test case for post_identity_group_alias

        Creates a new group alias, or updates an existing one.  # noqa: E501
        """
        pass

    def test_post_identity_group_alias_id_id(self):
        """Test case for post_identity_group_alias_id_id

        """
        pass

    def test_post_identity_group_id_id(self):
        """Test case for post_identity_group_id_id

        Update or delete an existing group using its ID.  # noqa: E501
        """
        pass

    def test_post_identity_group_name_name(self):
        """Test case for post_identity_group_name_name

        """
        pass

    def test_post_identity_lookup_entity(self):
        """Test case for post_identity_lookup_entity

        Query entities based on various properties.  # noqa: E501
        """
        pass

    def test_post_identity_lookup_group(self):
        """Test case for post_identity_lookup_group

        Query groups based on various properties.  # noqa: E501
        """
        pass

    def test_post_identity_oidc_config(self):
        """Test case for post_identity_oidc_config

        OIDC configuration  # noqa: E501
        """
        pass

    def test_post_identity_oidc_introspect(self):
        """Test case for post_identity_oidc_introspect

        Verify the authenticity of an OIDC token  # noqa: E501
        """
        pass

    def test_post_identity_oidc_key_name(self):
        """Test case for post_identity_oidc_key_name

        CRUD operations for OIDC keys.  # noqa: E501
        """
        pass

    def test_post_identity_oidc_key_name_rotate(self):
        """Test case for post_identity_oidc_key_name_rotate

        Rotate a named OIDC key.  # noqa: E501
        """
        pass

    def test_post_identity_oidc_role_name(self):
        """Test case for post_identity_oidc_role_name

        CRUD operations on OIDC Roles  # noqa: E501
        """
        pass

    def test_post_identity_persona(self):
        """Test case for post_identity_persona

        Create a new alias.  # noqa: E501
        """
        pass

    def test_post_identity_persona_id_id(self):
        """Test case for post_identity_persona_id_id

        Update, read or delete an alias ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
