# coding: utf-8

"""
    HashiCorp Vault API

    HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hashicorp_vault_client
from api.auth_api import AuthApi  # noqa: E501
from hashicorp_vault_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_auth_oidc_role_name(self):
        """Test case for delete_auth_oidc_role_name

        Delete an existing role.  # noqa: E501
        """
        pass

    def test_delete_auth_token_roles_role_name(self):
        """Test case for delete_auth_token_roles_role_name

        """
        pass

    def test_get_auth_oidc_config(self):
        """Test case for get_auth_oidc_config

        Read the current JWT authentication backend configuration.  # noqa: E501
        """
        pass

    def test_get_auth_oidc_oidc_callback(self):
        """Test case for get_auth_oidc_oidc_callback

        Callback endpoint to complete an OIDC login.  # noqa: E501
        """
        pass

    def test_get_auth_oidc_role(self):
        """Test case for get_auth_oidc_role

        Lists all the roles registered with the backend.  # noqa: E501
        """
        pass

    def test_get_auth_oidc_role_name(self):
        """Test case for get_auth_oidc_role_name

        Read an existing role.  # noqa: E501
        """
        pass

    def test_get_auth_token_accessors(self):
        """Test case for get_auth_token_accessors

        List token accessors, which can then be be used to iterate and discover their properties or revoke them. Because this can be used to cause a denial of service, this endpoint requires 'sudo' capability in addition to 'list'.  # noqa: E501
        """
        pass

    def test_get_auth_token_lookup(self):
        """Test case for get_auth_token_lookup

        This endpoint will lookup a token and its properties.  # noqa: E501
        """
        pass

    def test_get_auth_token_lookup_self(self):
        """Test case for get_auth_token_lookup_self

        This endpoint will lookup a token and its properties.  # noqa: E501
        """
        pass

    def test_get_auth_token_roles(self):
        """Test case for get_auth_token_roles

        This endpoint lists configured roles.  # noqa: E501
        """
        pass

    def test_get_auth_token_roles_role_name(self):
        """Test case for get_auth_token_roles_role_name

        """
        pass

    def test_post_auth_oidc_config(self):
        """Test case for post_auth_oidc_config

        Configure the JWT authentication backend.  # noqa: E501
        """
        pass

    def test_post_auth_oidc_login(self):
        """Test case for post_auth_oidc_login

        Authenticates to Vault using a JWT (or OIDC) token.  # noqa: E501
        """
        pass

    def test_post_auth_oidc_oidc_auth_url(self):
        """Test case for post_auth_oidc_oidc_auth_url

        Request an authorization URL to start an OIDC login flow.  # noqa: E501
        """
        pass

    def test_post_auth_oidc_role_name(self):
        """Test case for post_auth_oidc_role_name

        Register an role with the backend.  # noqa: E501
        """
        pass

    def test_post_auth_token_create(self):
        """Test case for post_auth_token_create

        The token create path is used to create new tokens.  # noqa: E501
        """
        pass

    def test_post_auth_token_create_orphan(self):
        """Test case for post_auth_token_create_orphan

        The token create path is used to create new orphan tokens.  # noqa: E501
        """
        pass

    def test_post_auth_token_create_role_name(self):
        """Test case for post_auth_token_create_role_name

        This token create path is used to create new tokens adhering to the given role.  # noqa: E501
        """
        pass

    def test_post_auth_token_lookup(self):
        """Test case for post_auth_token_lookup

        This endpoint will lookup a token and its properties.  # noqa: E501
        """
        pass

    def test_post_auth_token_lookup_accessor(self):
        """Test case for post_auth_token_lookup_accessor

        This endpoint will lookup a token associated with the given accessor and its properties. Response will not contain the token ID.  # noqa: E501
        """
        pass

    def test_post_auth_token_lookup_self(self):
        """Test case for post_auth_token_lookup_self

        This endpoint will lookup a token and its properties.  # noqa: E501
        """
        pass

    def test_post_auth_token_renew(self):
        """Test case for post_auth_token_renew

        This endpoint will renew the given token and prevent expiration.  # noqa: E501
        """
        pass

    def test_post_auth_token_renew_self(self):
        """Test case for post_auth_token_renew_self

        This endpoint will renew the token used to call it and prevent expiration.  # noqa: E501
        """
        pass

    def test_post_auth_token_revoke(self):
        """Test case for post_auth_token_revoke

        This endpoint will delete the given token and all of its child tokens.  # noqa: E501
        """
        pass

    def test_post_auth_token_revoke_accessor(self):
        """Test case for post_auth_token_revoke_accessor

        This endpoint will delete the token associated with the accessor and all of its child tokens.  # noqa: E501
        """
        pass

    def test_post_auth_token_revoke_orphan(self):
        """Test case for post_auth_token_revoke_orphan

        This endpoint will delete the token and orphan its child tokens.  # noqa: E501
        """
        pass

    def test_post_auth_token_revoke_self(self):
        """Test case for post_auth_token_revoke_self

        This endpoint will delete the token used to call it and all of its child tokens.  # noqa: E501
        """
        pass

    def test_post_auth_token_roles_role_name(self):
        """Test case for post_auth_token_roles_role_name

        """
        pass

    def test_post_auth_token_tidy(self):
        """Test case for post_auth_token_tidy

        This endpoint performs cleanup tasks that can be run if certain error conditions have occurred.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
